//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCDS.Web
{


    public partial class Dashboard
    {

        protected global::System.Web.UI.UpdatePanel upDashboard;

        protected global::System.Web.UI.Timer tmrAutoRefresh;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.SqlDataSource dsSummary;

        protected global::System.Web.UI.WebControls.FormView fvSummary;

        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        protected global::System.Web.UI.WebControls.TextBox txtFromDate;

        protected global::System.Web.UI.WebControls.TextBox txtToDate;

        protected global::System.Web.UI.WebControls.DropDownList ddlLoanType;

        protected global::System.Web.UI.WebControls.Button btnFilter;

        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.Button btnExportExcel;

        protected global::System.Web.UI.WebControls.GridView gvDashboard;
    }
}
