//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

namespace LOCDS.Web
{
    public partial class DecisionSheet
    {
        protected global::System.Web.UI.WebControls.Label lblApplicationId;
        protected global::System.Web.UI.WebControls.Label lblApplicantName;
        protected global::System.Web.UI.WebControls.Label lblRequestedAmount;
        protected global::System.Web.UI.WebControls.Label lblRecommendedDecision;
        protected global::System.Web.UI.WebControls.Label lblManualDecision;
        protected global::System.Web.UI.WebControls.Label lblApprovedAmount;
        protected global::System.Web.UI.WebControls.Label lblInterestRate;
        protected global::System.Web.UI.WebControls.Label lblRemarks;
        protected global::System.Web.UI.WebControls.Label lblDecidedBy;
        protected global::System.Web.UI.WebControls.Label lblDecidedAt;
    }
}
