//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCDS.Web
{
    public partial class LoanOfferPage
    {
        protected global::System.Web.UI.WebControls.HiddenField hfOfferExpiryUtc;
        protected global::System.Web.UI.WebControls.Label lblPageMessage;

        protected global::System.Web.UI.WebControls.Label lblApplicationId;
        protected global::System.Web.UI.WebControls.Label lblApprovedAmount;
        protected global::System.Web.UI.WebControls.Label lblInterestRate;
        protected global::System.Web.UI.WebControls.Label lblTenure;
        protected global::System.Web.UI.WebControls.Label lblEmi;

        protected global::System.Web.UI.WebControls.GridView gvAmortization;

        protected global::System.Web.UI.WebControls.Label lblPrincipal;
        protected global::System.Web.UI.WebControls.Label lblTotalInterest;
        protected global::System.Web.UI.WebControls.Label lblProcessingFee;
        protected global::System.Web.UI.WebControls.Label lblTotalCost;

        protected global::System.Web.UI.WebControls.DropDownList ddlEmiDate;
        protected global::System.Web.UI.WebControls.Button btnAcceptOffer;
        protected global::System.Web.UI.WebControls.Button btnRejectOffer;

        protected global::System.Web.UI.WebControls.Panel pnlDisbursementTracker;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl step1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl step2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl step3;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl step4;

        protected global::System.Web.UI.WebControls.TextBox txtOtp;
        protected global::System.Web.UI.WebControls.Label lblOtpMessage;
        protected global::System.Web.UI.WebControls.Button btnSendOtp;
        protected global::System.Web.UI.WebControls.Button btnConfirmAccept;
    }
}
