//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCDS.Web
{


    public partial class LoanApplicationPage
    {

        protected global::System.Web.UI.WebControls.Label lblProgressText;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divProgressBar;

        protected global::System.Web.UI.WebControls.Label lblGlobalMessage;

        protected global::System.Web.UI.WebControls.Wizard wizLoanApplication;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        protected global::System.Web.UI.WebControls.TextBox txtDob;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDob;

        protected global::System.Web.UI.WebControls.CustomValidator cvDobAge;

        protected global::System.Web.UI.WebControls.TextBox txtPan;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPan;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPan;

        protected global::System.Web.UI.WebControls.TextBox txtAadhaar;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAadhaar;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revAadhaar;

        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAddress;

        protected global::System.Web.UI.WebControls.DropDownList ddlEmploymentType;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmploymentType;

        protected global::System.Web.UI.WebControls.TextBox txtEmployer;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmployer;

        protected global::System.Web.UI.WebControls.TextBox txtAnnualIncome;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAnnualIncome;

        protected global::System.Web.UI.WebControls.RangeValidator rvAnnualIncome;

        protected global::System.Web.UI.WebControls.TextBox txtWorkExperience;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvWorkExperience;

        protected global::System.Web.UI.WebControls.RangeValidator rvWorkExperience;

        protected global::System.Web.UI.WebControls.FileUpload fuItr;

        protected global::System.Web.UI.WebControls.CustomValidator cvItrUpload;

        protected global::System.Web.UI.WebControls.DropDownList ddlPurpose;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPurpose;

        protected global::System.Web.UI.WebControls.TextBox txtAmount;

        protected global::System.Web.UI.WebControls.RangeValidator rvAmount;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAmount;

        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl rngAmount;

        protected global::System.Web.UI.WebControls.RadioButtonList rblTenure;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTenure;

        protected global::System.Web.UI.WebControls.CheckBox chkCoApplicant;

        protected global::System.Web.UI.WebControls.Label lblEmiPreview;

        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        protected global::System.Web.UI.WebControls.Literal litSummaryName;

        protected global::System.Web.UI.WebControls.Literal litSummaryDob;

        protected global::System.Web.UI.WebControls.Literal litSummaryPan;

        protected global::System.Web.UI.WebControls.Literal litSummaryAddress;

        protected global::System.Web.UI.WebControls.Literal litSummaryEmployment;

        protected global::System.Web.UI.WebControls.Literal litSummaryIncome;

        protected global::System.Web.UI.WebControls.Literal litSummaryExperience;

        protected global::System.Web.UI.WebControls.Literal litSummaryPurpose;

        protected global::System.Web.UI.WebControls.Literal litSummaryAmount;

        protected global::System.Web.UI.WebControls.Literal litSummaryTenure;

        protected global::System.Web.UI.WebControls.Literal litSummaryCoApplicant;

        protected global::System.Web.UI.WebControls.CheckBox chkDeclaration;

        protected global::System.Web.UI.WebControls.CustomValidator cvDeclaration;

        protected global::System.Web.UI.WebControls.Label lblReferenceNumber;
    }
}
