//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCDS.Web
{


    public partial class Login
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm formLogin;

        protected global::System.Web.UI.HtmlControls.HtmlInputHidden __RequestVerificationToken;

        protected global::System.Web.UI.ScriptManager smLogin;

        protected global::System.Web.UI.UpdatePanel upLogin;

        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsername;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        protected global::System.Web.UI.WebControls.Panel pnlCaptcha;

        protected global::System.Web.UI.WebControls.Label lblCaptchaQuestion;

        protected global::System.Web.UI.WebControls.TextBox txtCaptcha;

        protected global::System.Web.UI.WebControls.Label lblCaptchaHint;

        protected global::System.Web.UI.WebControls.CheckBox chkRememberMe;

        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.LinkButton lnkForgotPassword;

        protected global::System.Web.UI.WebControls.Label lblFeedback;

        protected global::System.Web.UI.WebControls.ValidationSummary vsLogin;
    }
}
