//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCDS.Web
{


    public partial class SiteMaster
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.HtmlControls.HtmlInputHidden __RequestVerificationToken;

        protected global::System.Web.UI.ScriptManager MainScriptManager;

        protected global::System.Web.UI.WebControls.Label lblLoggedInUser;

        protected global::System.Web.UI.WebControls.Label lblRoleBadge;

        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.WebControls.PlaceHolder phApplicantMenu;

        protected global::System.Web.UI.WebControls.PlaceHolder phCreditOfficerMenu;

        protected global::System.Web.UI.WebControls.PlaceHolder phUnderwriterMenu;

        protected global::System.Web.UI.WebControls.PlaceHolder phBranchManagerMenu;

        protected global::System.Web.UI.WebControls.SiteMapPath MainBreadcrumb;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        protected global::System.Web.UI.WebControls.HiddenField hfSessionTimeoutMinutes;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
    }
}
