//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

namespace LOCDS.Web
{
    public partial class UnderwritingDecisionPage
    {
        protected global::System.Web.UI.UpdatePanel upDecision;
        protected global::System.Web.UI.WebControls.Label lblPageMessage;
        protected global::System.Web.UI.WebControls.Label lblApplicantName;
        protected global::System.Web.UI.WebControls.Label lblApplicantDob;
        protected global::System.Web.UI.WebControls.Label lblApplicantPan;
        protected global::System.Web.UI.WebControls.Label lblEmployment;
        protected global::System.Web.UI.WebControls.Label lblRiskTier;
        protected global::System.Web.UI.WebControls.Label lblScoreCibil;
        protected global::System.Web.UI.WebControls.Label lblDefaultCibil;
        protected global::System.Web.UI.WebControls.Label lblScoreExperian;
        protected global::System.Web.UI.WebControls.Label lblDefaultExperian;
        protected global::System.Web.UI.WebControls.Label lblScoreEquifax;
        protected global::System.Web.UI.WebControls.Label lblDefaultEquifax;
        protected global::System.Web.UI.WebControls.Label lblMonthlyIncome;
        protected global::System.Web.UI.WebControls.Label lblExistingEmi;
        protected global::System.Web.UI.WebControls.Label lblProposedEmi;
        protected global::System.Web.UI.WebControls.Label lblFoir;
        protected global::System.Web.UI.WebControls.Label lblApplicationId;
        protected global::System.Web.UI.WebControls.Label lblPurpose;
        protected global::System.Web.UI.WebControls.Label lblRequestedAmount;
        protected global::System.Web.UI.WebControls.Label lblTenure;
        protected global::System.Web.UI.WebControls.GridView gvObligations;
        protected global::System.Web.UI.WebControls.Label lblLtv;
        protected global::System.Web.UI.WebControls.Label lblAutoRecommendation;
        protected global::System.Web.UI.WebControls.Label lblAutoRemarks;
        protected global::System.Web.UI.WebControls.RadioButtonList rblDecision;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDecision;
        protected global::System.Web.UI.WebControls.TextBox txtApprovedAmount;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvApprovedAmount;
        protected global::System.Web.UI.WebControls.TextBox txtInterestRate;
        protected global::System.Web.UI.WebControls.CheckBox chkOverrideRate;
        protected global::System.Web.UI.WebControls.TextBox txtRateJustification;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.CustomValidator cvRemarks;
        protected global::System.Web.UI.WebControls.CheckBoxList cblSupportingDocs;
        protected global::System.Web.UI.WebControls.Button btnShowConfirm;
        protected global::System.Web.UI.WebControls.Button btnPrintSheet;
        protected global::System.Web.UI.WebControls.GridView gvHistory;
        protected global::System.Web.UI.WebControls.Button btnSubmitDecision;
    }
}
